### ISSUE TITLE
[popup] css 방향이나 팁

### ISSUE THREAD

**Issue by bomi5375** [likelion-lab1/vanilla-project#32]
어떤 걸 사용해야 하는지 헤매는 중이라 help 올렸어요

# Issue : 버그보고

**Comment by bsw98** [comment]
@import url(./reset.css);
@import url(./normalize.css);
@import url('https://cdn.jsdelivr.net/gh/orioncactus/pretendard/dist/web/static/pretendard.css');

/* 숨김 컨텐츠 */
.a11y-hidden, legend {
  background-color: red;
  position: absolute;
  width: 1px;
  height: 1px;
  margin: -1px;
  overflow: hidden;
  clip-path: polygon(0 0, 0 0, 0 0);
}

html {
  font-size: 16px;
}

/* 링크 스타일 */
a {
  color: inherit;
  text-decoration: none;
}

/* 기본 스타일 */
*, *::before, *::after {
  box-sizing: border-box;
}

/* 공통 바디 스타일 */
body {
  font-family: "Pretendard Variable", Pretendard, -apple-system, BlinkMacSystemFont, system-ui, Roboto, "Helvetica Neue", "Segoe UI", "Apple SD Gothic Neo", "Noto Sans KR", "Malgun Gothic", "Apple Color Emoji", "Segoe UI Emoji", "Segoe UI Symbol", sans-serif;
}

/* 공통 */
.center{
  display: flex;
  justify-content: center;
  text-align: center;
  width: 1050px;
  margin:0 auto;
 /* margin: 0 435px; */
}
/* 헤더 */
.header{
  height: 125px;
  background-color: antiquewhite;
}
/* 네비게이션 */
.navigation{
  height: 72px;
  background-color: aqua;
}
/* 메인 */
.main{
  height: 1421px;
  background-color: aquamarine;
}

/* 푸터 */
.footer{
  height:737px;
  background-color: beige;
}
/* 배너 */
.lineBanner{
  display: flex;
  justify-content: center;
  align-items: center;
  height: 219px;
}

.lineBanner1{
  width: 1050px;
  max-height: 100%;
}
.isActive{
  display:none;
}
.popup{
  
  display: flex;
  flex-flow:column;
  justify-content: center;
  text-align: center;
  top:0;
  position: fixed;
  width: 100%;
  height: 100%;
  background-color: rgba(1,1,1,0.2);
  cursor: pointer;
  z-index: 10;
}
.popupLink{
  background-color: rgb(19, 58, 117);
  width: 100px;
  height: 100px;
}


.popupButton{
  margin:0 auto;
  width: 440px;
  height: 86px;
  display: flex;
  
  
  
}

.popupButtonLeft{
  background-color: rgb(111, 31, 107);
  border: none;
  flex: 1;
  width: 50%;
  /* align-items: center;
  justify-content: center; */
}

.popupButtonRight{
  background-color: rgb(18, 144, 45);
  flex: 1;
  border: none;
  width: 50%;
  /* align-items: center;
  justify-content: center; */
}

**Comment by bomi5375** [comment]
해결완료
